version: "3.1"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: measures
      POSTGRES_USER: measures
      POSTGRES_DB: measures
    volumes:
      - ./components/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
